name: slides

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mpetienne/r-courses:0.30

    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install R packages
        run: |
          install.packages("remotes")
          install.packages(c("devtools","plotly","ggpubr","gifski"))
          install.packages(c("ggfortify"))
          install.packages('maps')
          install.packages(c("rnaturalearth","rnaturalearthdata"))
          install.packages(c("kableExtra", 'flexdashboard'))
          remotes::install_github("ropensci/osmdata")
          remotes::install_github("MarieEtienne/coursesdata")
          install.packages("leaflet")


        shell: Rscript {0}
      - name: Generate slides
        run: Rscript R/render.R
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./render
